export interface ProdutoItem {
  nome: string;
  pontos: number;
}

export interface ExecucaoItem {
  nome: string;
  pontos: number;
}

export interface CanalConfig {
  produtos: ProdutoItem[];
  execucao: ExecucaoItem[];
}

export const canalProdutosExecucao: Record<string, CanalConfig> = {
  "Padaria/Confeitaria": {
    produtos: [
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 30 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 15 },
      { nome: "AMSTEL LT 473ML", pontos: 15 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 20 },
      { nome: "FYS", pontos: 20 },
    ],
    execucao: [
      { nome: "AMSTEL NO CARDÁPIO ou ADESIVO DE GELADEIRA", pontos: 30 },
      { nome: "HEINEKEN NO CARDÁPIO ou ADESIVO DE GELADEIRA", pontos: 15 },
      { nome: "HEINEKEN 0,0% NO CARDÁPIO ou ADESIVO DE GELADEIRA", pontos: 15 },
      { nome: "FYS NO CARDÁPIO ou ADESIVO DE GELADEIRA", pontos: 20 },
      { nome: "ADESIVO DE GELADEIRA MULTIMARCAS", pontos: 20 },
    ],
  },
  "Armazém/Mercearia": {
    produtos: [
      { nome: "HEINEKEIN LN 330ML: RGB/DESC", pontos: 25 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 15 },
      { nome: "HEINEKEN LT 473ML", pontos: 20 },
      { nome: "AMSTEL LT 473ML", pontos: 20 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "HEINEKEN RGB 600ML/CHOPP", pontos: 25 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 10 },
      { nome: "HEINEKEIN LT 350ML", pontos: 5 },
    ],
    execucao: [
      { nome: "CARTAZ ou ADESIVO DE GELAD. AMSTEL", pontos: 25 },
      { nome: "CARTAZ ou ADESIVO DE GELAD. HEINEKEN", pontos: 15 },
      { nome: "CARTAZ ou ADESIVO DE GELAD. HEINEKEN 0,0", pontos: 20 },
      { nome: "CARTAZ ou ADESIVO DE GELAD. FYS", pontos: 20 },
      { nome: "CARTAZ MULTIMARCAS", pontos: 10 },
      { nome: "ADESIVO DE GELADEIRA MULTIMARCAS", pontos: 10 },
      { nome: "FAIXA BAR ou CARTAZ DE ILHA AMSTEL", pontos: 25 },
      { nome: "CARTAZ ILHA HEINEKEN", pontos: 10 },
      { nome: "CARTAZ MULTIMARCAS (2)", pontos: 5 },
    ],
  },
  "Adega": {
    produtos: [
      { nome: "HEINEKEN LT 473ML", pontos: 10 },
      { nome: "EISENBAHN 600ML: PIL/UNF", pontos: 15 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 5 },
      { nome: "AMSTEL RGB 1L, 600ML, CHOPP OU 300ML", pontos: 20 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 30 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF (2)", pontos: 15 },
    ],
    execucao: [
      { nome: "CARTAZ ou CARTOP AMSTEL", pontos: 30 },
      { nome: "CARTAZ ou CARTOP FYS", pontos: 15 },
    ],
  },
  "Lanchonete": {
    produtos: [
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 30 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 15 },
      { nome: "AMSTEL LT 473ML", pontos: 15 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 20 },
      { nome: "FYS", pontos: 20 },
      { nome: "HEINEKEN RGB 600ML/CHOPP", pontos: 20 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC (2)", pontos: 10 },
      { nome: "EISENBAHN 600ML: PIL/UNF", pontos: 15 },
    ],
    execucao: [
      { nome: "CARTAZ ou CARTOP AMSTEL", pontos: 30 },
      { nome: "CARTAZ ou CARTOP FYS", pontos: 15 },
      { nome: "AMSTEL NO CARDÁPIO", pontos: 15 },
      { nome: "HEINEKEN NO CARDÁPIO", pontos: 20 },
      { nome: "HEINEKEN 0,0% NO CARDÁPIO", pontos: 20 },
      { nome: "QUADRO, CARTAZ ou CARTOP AMSTEL", pontos: 20 },
      { nome: "QUADRO, CARTAZ ou CARTOP FYS", pontos: 10 },
      { nome: "5 UNID. DE BALDE ou CERVEGELA AMSTEL", pontos: 15 },
    ],
  },
  "Restaurante C/D": {
    produtos: [
      { nome: "AMSTEL RGB: 1L, 600ML, CHOPP, 300ML", pontos: 15 },
      { nome: "AMSTEL LN: 330ML/275ML(ULTRA)", pontos: 10 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "HEINEKEN 0,0% LT 350ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN 600ML ou CHOPP", pontos: 10 },
      { nome: "PRAYA LN LAGER 330ML", pontos: 10 },
      { nome: "HEINEKEN RGB: 600 ou CHOPP", pontos: 20 },
      { nome: "HEINEKEN LN 330ML: RGB OU DESC", pontos: 20 },
    ],
    execucao: [
      { nome: "AMSTEL NO CARDÁPIO", pontos: 15 },
      { nome: "HEINEKEN NO CARDÁPIO", pontos: 10 },
      { nome: "HEINEKEN 0,0% NO CARDÁPIO", pontos: 10 },
      { nome: "FYS NO CARDÁPIO", pontos: 10 },
      { nome: "LUMINOSO OU QUADRO BADEN", pontos: 10 },
      { nome: "LUMINOSO OU QUADRO HEINEKEN", pontos: 10 },
    ],
  },
  "Restaurante A/B": {
    produtos: [
      { nome: "EISENBAHN LN 330ML: PIL/UNF", pontos: 10 },
      { nome: "AMSTEL LN: 330ML/275ML(ULTRA)", pontos: 10 },
      { nome: "HEINEKEN 0,0% LONG 330ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "HEINEKEN RGB: CHOPP OU 600ML", pontos: 30 },
      { nome: "HEINKEIN LT 473ML", pontos: 10 },
      { nome: "EISENBAHN 600ML: PIL/UNF", pontos: 10 },
    ],
    execucao: [
      { nome: "5 UNID. DE BALDE OU CERVEGELA BADEN", pontos: 20 },
      { nome: "5 UNID. DE BALDE OU CERVEGELA HEINEKEN", pontos: 20 },
      { nome: "BADEN BADEN NO CARDÁPIO", pontos: 10 },
      { nome: "AMSTEL NO CARDÁPIO", pontos: 10 },
      { nome: "HEINEKEN NO CARDÁPIO", pontos: 10 },
      { nome: "HEINEKEN 0,0 NO CARDÁPIO", pontos: 10 },
      { nome: "FYS NO CARDÁPIO", pontos: 0 },
    ],
  },
  "Bar C/D": {
    produtos: [
      { nome: "HEINEKEN RGB: CHOPP OU 600ML", pontos: 30 },
      { nome: "HEINKEIN LT 473ML", pontos: 10 },
      { nome: "EISENBAHN 600ML: PIL/UNF", pontos: 10 },
      { nome: "EISENBAHN LATÃO 473ML: PIL/UNF", pontos: 10 },
      { nome: "AMSTEL RGB: CHOPP, 1L, 600ML OU 300ML", pontos: 20 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN: 600ML ou CHOPP", pontos: 5 },
      { nome: "PRAYA LN 330ML LAGER", pontos: 5 },
    ],
    execucao: [
      { nome: "5 UNID. DE BALDE ou CERVEGELA AMSTEL", pontos: 30 },
      { nome: "CARTOP, CARTAZ ou FAIXA BAR AMSTEL", pontos: 10 },
      { nome: "CARTOP HEINEKEN", pontos: 10 },
      { nome: "CARTOP, CARTAZ ou FAIXA BAR FYS", pontos: 10 },
      { nome: "LUMINOSO AMSTEL", pontos: 5 },
      { nome: "QUADRO HEINEKEN", pontos: 5 },
    ],
  },
  "Bar A/B": {
    produtos: [
      { nome: "HEINEKEN RGB: 600ML ou CHOPP", pontos: 25 },
      { nome: "HEINENEN LN 330ML: RGB OU DESC", pontos: 10 },
      { nome: "EISENBAHN 600ML PIL/UNF", pontos: 15 },
      { nome: "AMSTEL RGB: 1L, 600 ou CHOPP ou 300ML", pontos: 20 },
      { nome: "AMSTEL LN: 330ML/275ML(ULTRA)", pontos: 5 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 10 },
      { nome: "FYS", pontos: 5 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 40 },
      { nome: "PRAYA LN 330ML", pontos: 10 },
    ],
    execucao: [
      { nome: "5 UNID. DE BALDE AMSTEL", pontos: 25 },
      { nome: "5 UNID. DE CERVEGELA AMSTEL", pontos: 10 },
      { nome: "BADEN NO CARDÁPIO", pontos: 15 },
      { nome: "HEINEKEN NO CARDÁPIO", pontos: 20 },
      { nome: "AMSTEL NO CARDÁPIO", pontos: 5 },
      { nome: "FYS NO CARDÁPIO", pontos: 10 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC NO CARDÁPIO", pontos: 40 },
      { nome: "PRAYA LN 330ML NO CARDÁPIO", pontos: 10 },
    ],
  },
  "Entretenimento Espec": {
    produtos: [
      { nome: "AMSTEL LT 473ML", pontos: 15 },
      { nome: "AMSTEL LN: 330ML/275ML(ULTRA)", pontos: 10 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 15 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN LT 350ML", pontos: 5 },
      { nome: "BLUE MOON LT/LN", pontos: 5 },
      { nome: "PRAYA LN", pontos: 5 },
      { nome: "SOL LN", pontos: 5 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 20 },
      { nome: "HEINEKEN LT 473ML", pontos: 15 },
    ],
    execucao: [
      { nome: "AMSTEL LT 473ML NO CARDÁPIO", pontos: 15 },
      { nome: "AMSTEL LN: 330ML/275ML(ULTRA) NO CARDÁPIO", pontos: 10 },
      { nome: "HEINEKEN 0,0% LN 330ML NO CARDÁPIO", pontos: 15 },
      { nome: "FYS NO CARDÁPIO", pontos: 10 },
      { nome: "LUMINOSO HEINEKEN 0,0%", pontos: 5 },
      { nome: "CAN BASE AMSTEL", pontos: 5 },
      { nome: "CAN BASE BADEN", pontos: 5 },
      { nome: "CAN BASE HEINEKEN", pontos: 5 },
      { nome: "CAN BASE HEINEKEN 0,0%", pontos: 20 },
      { nome: "CAN BASE FYS", pontos: 15 },
    ],
  },
  "Loja de Conveniência": {
    produtos: [
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 20 },
      { nome: "HEINEKEN LT 473ML", pontos: 15 },
      { nome: "HEINEKEIN SHOT 250ML", pontos: 5 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 10 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN LT 350ML", pontos: 10 },
      { nome: "PRAYA LN", pontos: 10 },
      { nome: "HEINEKEN LN 330ML: RGB/DESC (2)", pontos: 25 },
    ],
    execucao: [
      { nome: "ADESIVO DE GELADEIRA AMSTEL", pontos: 15 },
      { nome: "ADESIVO DE GELDEIRA BADEN", pontos: 5 },
      { nome: "ADESIVO DE GELADEIRA HEINEKEN", pontos: 10 },
      { nome: "ADESIVO DE GELADEIRA HEINEKEN 0,0%", pontos: 10 },
      { nome: "ADESIVO DE GELADEIRA FYS", pontos: 10 },
      { nome: "ADESIVO DE GELADEIRA MULTIMARCAS", pontos: 0 },
      { nome: "WOOBLER ou STOPPER", pontos: 10 },
      { nome: "CARTAZ ILHA", pontos: 10 },
      { nome: "DISPLAY/EXPOSITOR", pontos: 25 },
    ],
  },
  "Mini A/B": {
    produtos: [
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 25 },
      { nome: "HEINEKEIN LT 350ML", pontos: 15 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 10 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "HEINEKEIN LN 0.0%", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN LT 350M", pontos: 5 },
      { nome: "SOL LN", pontos: 5 },
    ],
    execucao: [
      { nome: "CAPA DE PALLET ou BOBINA DE FORRAÇÃO", pontos: 15 },
      { nome: "WOOBLER ou STOPPER", pontos: 5 },
      { nome: "CARTAZ ILHA", pontos: 5 },
      { nome: "DISPLAY/EXPOSITOR", pontos: 25 },
    ],
  },
  "Mini C/D": {
    produtos: [
      { nome: "HEINEKEN LN 330ML: RGB/DESC", pontos: 25 },
      { nome: "HEINEKEIN LT 473ML", pontos: 15 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 10 },
      { nome: "AMSTEL LT 473ML", pontos: 15 },
      { nome: "HEINEKEIN LT 0.0% 350ML", pontos: 15 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN LT 350ML", pontos: 5 },
    ],
    execucao: [
      { nome: "CAPA DE PALLET ou BOBINA DE FORRAÇÃO", pontos: 15 },
      { nome: "WOOBLER ou STOPPER", pontos: 5 },
    ],
  },
  "Super A/B": {
    produtos: [
      { nome: "PRAYA LN", pontos: 5 },
      { nome: "HEINEKEIN LN 330ML: RGB/DESC", pontos: 20 },
      { nome: "HEINEKEN LONG SHOT", pontos: 5 },
      { nome: "HEINEKEN LT 350ML", pontos: 5 },
      { nome: "HEINEKEN LT 473ML", pontos: 10 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 10 },
      { nome: "EISENBAHN LT 350ML: PIL/UNF", pontos: 5 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "AMSTEL LT 350ML", pontos: 5 },
      { nome: "HEINEKEN 0,0% LN 330ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
      { nome: "BADEN LT 350ML", pontos: 5 },
      { nome: "SOL LN", pontos: 5 },
    ],
    execucao: [
      { nome: "CARTAZ ILHA", pontos: 5 },
      { nome: "DISPLAY/EXPOSITOR", pontos: 20 },
      { nome: "CAPA DE PALLET ou BOBINA DE FORRAÇÃO", pontos: 5 },
      { nome: "WOOBLER ou STOPPER", pontos: 5 },
    ],
  },
  "Super C/D": {
    produtos: [
      { nome: "HEINEKEIN LN 330ML: RGB/DESC", pontos: 20 },
      { nome: "HEINEKEN LONG SHOT", pontos: 5 },
      { nome: "HEINEKEN LT 350ML", pontos: 5 },
      { nome: "HEINEKEN LT 473ML", pontos: 10 },
      { nome: "EISENBAHN LT 473ML: PIL/UNF", pontos: 10 },
      { nome: "EISENBAHN LT 350ML: PIL/UNF", pontos: 5 },
      { nome: "AMSTEL LT 473ML", pontos: 10 },
      { nome: "AMSTEL LT 350ML", pontos: 5 },
      { nome: "HEINEKEN 0,0% LT 350ML", pontos: 10 },
      { nome: "FYS", pontos: 10 },
    ],
    execucao: [
      { nome: "DISPLAY/EXPOSITOR", pontos: 20 },
      { nome: "CAPA DE PALLET ou BOBINA DE FORRAÇÃO", pontos: 5 },
      { nome: "WOOBLER ou STOPPER", pontos: 5 },
    ],
  },
};
