-- Reconstrução Completa da Tabela de PDVs (Migração para Formato Limpo Unibeer)
-- ATENÇÃO: Executar isso deletará todos os PDVs cadastrados hoje.

-- 1. Drop da tabela antiga
DROP TABLE IF EXISTS public.pdvs CASCADE;

-- 2. Criação da nova tabela otimizada
CREATE TABLE public.pdvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filial TEXT,
    codigo TEXT NOT NULL,
    cod_vendedor TEXT,
    nome_vendedor TEXT,
    cod_supervisor INTEGER,
    nome_supervisor TEXT,
    cod_gerente INTEGER,
    nome_gerente_vendas TEXT,
    nome_gerente_comercial TEXT,
    rota TEXT,
    canal TEXT,
    cnpj_cpf TEXT,
    sigla TEXT,
    razao_social TEXT,
    porte TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Recriação das regras de Segurança (RLS)
ALTER TABLE public.pdvs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso de Leitura Público PDVS" 
ON public.pdvs FOR SELECT 
USING (true);

CREATE POLICY "Insercao Autenticada PDVS" 
ON public.pdvs FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Delecao Autenticada PDVS" 
ON public.pdvs FOR DELETE 
USING (auth.role() = 'authenticated');

-- Indices para facilitar pesquisa por empresa e codigo e supervisor
CREATE INDEX idx_pdvs_empresa ON public.pdvs(empresa_id);
CREATE INDEX idx_pdvs_codigo ON public.pdvs(codigo);
CREATE INDEX idx_pdvs_supervisor ON public.pdvs(cod_supervisor);
CREATE INDEX idx_pdvs_gerente ON public.pdvs(cod_gerente);
